[project]
name = "amd-ai-sprint-hackathon"
version = "0.1.0"
description = "FastAPI Scheduling Agent Service"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
    "pydantic>=2.0.0",
    "python-multipart>=0.0.6"
]
